### ISSUE TITLE
how to color diffrent colors to upper and lower parts

### ISSUE THREAD

**Issue by zaaach** [vipulasri/TicketView#19]
![微信截图_20190929141241](https://user-images.githubusercontent.com/9695127/65827289-470c4f80-e2c3-11e9-935f-6cbac4ee5ffb.png)

**Comment by vipulasri** [comment]
@zaaach This is not possible as of now. Will look into this.

**Comment by zaaach** [comment]
Thank you for your reply and look forward to the next update of this library.

**Comment by vipulasri** [comment]
This feature is now available in `v1.0.9`.
