### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by Thecave3** [vipulasri/TicketView#3]
Hi, I'm trying to use your library in my application but I'm having some issues about:
1) How can I populate the view? I've created in my XML layout, but how can I set an image and the various information I have to display?
2) Is it possible to have a sample code (the one inside your play store's app would be perfect)?
3) Also, I saw some code in this repo for example. Is it possible to use and have it in Java?
4) A better documentation or a wiki maybe is the most missing point in this library.

Let me know and thanks for your work!

**Comment by vipulasri** [comment]
@Thecave3 The code for sample app on play store is already there in repo.  You can find it here [Sample App](https://github.com/vipulasri/TicketView/tree/master/sample)
