### ISSUE TITLE
Ability to export Ticket as an image

### ISSUE THREAD

**Issue by brookmg** [vipulasri/TicketView#30]
- The title says it all. Is there a built-in functionality that lets the user export the View into some kind of an image? The basic idea is to make it shareable through android intent. I am willing to work on something if it's not yet available or not in the works.

**Comment by vipulasri** [comment]
That will be a good feature but I think that will move the library slightly away from the main concept. 
Also, having this feature can bloat the library as not everyone will want to have that functionality. 
Moreover there a good libraries available which you can use in combination to get the desired result. 

Check this out: https://github.com/nisrulz/screenshott
