### ISSUE TITLE
backgroung color and text on ticket

### ISSUE THREAD

**Issue by bramaramba** [vipulasri/TicketView#34]
HI, I am unable to view on ticket view. if i used transparent background it gives gray color background in devices. please help me with including layout over ticketview

**Comment by vipulasri** [comment]
@bramaramba Can you please share the following to better understand the issue:
1. Code you have implemented
2. Current result
3. Desired result

**Comment by bramaramba** [comment]
Hi Vipulasri , Thank you for your reply.
this is my desired output

[image: image.png]


but, i am getting in mobile

[image: image.png]

**Comment by bramaramba** [comment]
[image: image.png]

**Comment by vipulasri** [comment]
@bramaramba please attach the proper files, I am unable to view the images.

**Comment by bramaramba** [comment]
HI this is my xml

**Comment by vipulasri** [comment]
@bramaramba Please add proper files/code. You are using email to comment on this issue which is not adding content to the issue.

**Comment by bramaramba** [comment]
hi, just tell me how to add text view on your ticketview

**Comment by vipulasri** [comment]
@bramaramba sample is already provided in the codebase. Please have a look at that.

**Comment by bramaramba** [comment]
You displayed just ticview and properties.  I checked. not textview.


Thanks again
