### ISSUE TITLE
how to use this view?

### ISSUE THREAD

**Issue by hosseinjafari9574** [vipulasri/TicketView#7]
Hi Vipul Asri, thanks for this nice view

but i have a question about how to use this view?

is there any gradle work or something to get this view as a library?

thanks again dude :)

**Comment by vipulasri** [comment]
Yes, you can access this library by including it in your 
```
build.gradle
``` .
You can also see the sample code in the repository on how to use it.

**Comment by hosseinjafari9574** [comment]
sorry bro, I made a mistake to send this issue, I had some open page in my internet explorer and accidentally send this issue in your project. sorry again

and thanks for your nice ticket View
